export const devIcons = [
  { iconName: "devicon-java-plain", name: "Java" },
  { iconName: "devicon-python-plain", name: "Python" },
  { iconName: "devicon-cplusplus-plain", name: "C++" },
  { iconName: "devicon-spring-plain", name: "Spring Boot" },
  { iconName: "devicon-apachekafka-original", name: "Kafka" },
  { iconName: "devicon-react-original", name: "React.js" },
  { iconName: "devicon-redux-original", name: "Redux" },
  { iconName: "devicon-kubernetes-plain", name: "Kubernetes" },
  { iconName: "devicon-docker-plain", name: "Docker" },
  { iconName: "devicon-prometheus-original", name: "Prometheus" },
  { iconName: "devicon-oracle-original", name: "Oracle" },
  { iconName: "devicon-mysql-plain", name: "MySQL" },
  { iconName: "devicon-redis-plain", name: "Redis" },
  { iconName: "devicon-pytorch-original", name: "Pytorch" },
  { iconName: "devicon-tensorflow-original", name: "Tensorflow" },
  { iconName: "devicon-amazonwebservices-original", name: "AWS" },
  { iconName: "devicon-googlecloud-plain", name: "GCP" },
  { iconName: "devicon-html5-plain", name: "HTML" },
  { iconName: "devicon-javascript-plain", name: "JavaScript" },
  { iconName: "devicon-tailwindcss-plain", name: "Tailwind CSS" },
  { iconName: "devicon-typescript-original", name: "TypeScript" },
  { iconName: "devicon-css3-plain", name: "CSS" },
  { iconName: "devicon-graphql-plain", name: "GraphQL" },
  { iconName: "devicon-nodejs-plain", name: "Node.js" },
  { iconName: "devicon-nextjs-original", name: "Next.js" },
  { iconName: "devicon-ionic-original", name: "Ionic" },
  { iconName: "devicon-git-plain", name: "Git" },
  { iconName: "devicon-splunk-line", name: "Splunk" },
  { iconName: "devicon-jenkins-line", name: "Jenkins" },
  { iconName: "devicon-elasticsearch-plain", name: "Elasticsearch" },
];
